language: python
sudo: false
matrix:
  include:
  - python: 3.6
install:
- pip install jupyter pelican markdown beautifulsoup4 nbconvert ipython
script:
- git config --global user.email "TravisBot@nomail"
- git config --global user.name "TravisBot"
- git config --global push.default simple
- git clone --recursive https://github.com/flothesof/PelicanBlog
- cd PelicanBlog
- ls
- make publish
- mkdir _build
- cd _build
- git clone https://github.com/flothesof/flothesof.github.io.git
- cd ..
- make deploy_travis
env:
  global:
  - secure: EgSitnCIxdBHifD4Wl1zFHSEUeA22EXTcKAUjNXjRr8ZrAICoaroy+IdPgxkr/lDX0PQeE/Pca2tZ49+BuJn+eaL6M3HOAAo4HFV+KdT+bLMOGDqr750vGrFoIbRPCFM6KjGAghJlAwHHe7NW2/guKY50hJi/TiVdWADeAJHjVPT+7Lh0qGarjIPXkNwm5pH9jlUh+OjiQj3UA0j8misCL/sxE20Vloe3BuDv6JMDe8AxHd8CTR+9QtiVnmDa1O1woc9uSOjLegJXTjTuxZ1bXn+pMnlB6vjEiUu9218/jzZovpFLBDYYgEblQrK6sli1I+B0/3+F7OjPbQ7OIXJ4iM0Sy968b9Ggc0RKmuDBzDOJ782MhTYPI2OQhh4M06yy0l43YSxCDEeOFesx37kpUsB9DJYHFyxU9i6ECcsZpFnsL7C8DxfKKu7sjb/zmMr0lQnukdwrNztvhMgKawIpvDuAwU3hAZ+t559kanob+WokVdo1CwrxqG4OURMgAu20ykkjnQrFqIDZ4GJiFVYaIr/4nz3CngaLwgI+4NU49H7ZPEL1vRRN3wPNPKjrn2db55xObszCbcETtJwUTaV1zPox7ink7moa7JxsF5iea3QPw0SsfxUbEGiGffK5s7xcoMd6zd1AvSRMZmIJOFJwtusgmwIvsCeL1oqxmeyx3k=
