# inspired by 
language: python
sudo: false

matrix:
  include:
    - python: 3.4

install:
  - pip install jupyter pelican markdown


script:
  - git config --global user.email "TravisBot@nomail"
  - git config --global user.name "TravisBot"
  - git config --global push.default simple
  - cd ..
  - git clone https://github.com/flothesof/PelicanBlog
  - cd PelicanBlog/content/posts
  - git pull
  - cd ../.. 
  - make publish
  - make deploy_mac

