language: python
sudo: false
matrix:
  include:
  - python: 3.5
install:
- pip install jupyter pelican markdown
script:
- git config --global user.email "TravisBot@nomail"
- git config --global user.name "TravisBot"
- git config --global push.default simple
- git clone --recursive https://github.com/flothesof/PelicanBlog
- cd PelicanBlog
- ls
- make publish
- mkdir _build
- cd _build
- git clone https://github.com/flothesof/flothesof.github.io.git
- cd ..
- make deploy_travis
env:
  global:
    secure: Ev60wMw+Yxr+ojXTPuu1fYpFVnmlwRYuj1VtRjrhSHLrO0WoMFtzIBI9axNEQY7nXp3L5pQnT/b3ifjYfnAIrhzuTCQXgDlYHFM8NH1eD1y4u0lL9DkMavg8BME0m5KmVDk9vIQfIyBbhJvadkD/3Y1XBSPWotMKGFHQXGmUiQzfhoHtHj1hrdER+BY8FeWmEqXJPX0dbd5BlSGCAhkL/oG56V9PRD3CPB466yXaXcEYyuORIIIzLG5A2p8w9Qy4tL8yLUYthIq5DCCPMF3VlMls4XCB9MHAZAt5LJg0xxN0SugBMqjlnXJ3M8j6LMLV+4cdOSMhpO8POYu4/VyFq4y13p4gv3Of0NIxy+AlRfCPjwBSIaH1hfMXz7jnD8SirNX6l48ytQ/A3iVpEcezwU0kysfnyVHLssjTKFAsbpEBoesxmqP7vcyzwsKg71KGWbobhO0nLQBpWLtzy59v0CE1yCer+lxH6oq54VDw40k2kIUmFO8BE6Io1P8rhBq2qifHQSJl6aFLp4tCsKl75QWndUTd06HNC01g97+r2u52++wBn4aMcdiBnzNeiK5BkVxWdzDFtcLDWLe9LIwJsJY6j3YWt6WqLfjI+b614RMXmOTFk/GE7UrexS5I5EmSW7O70yMTYp0BIOh/2b9KeXtdvYJkiaANRjfbsOdHky4=
