# inspired by 
language: python
sudo: false

matrix:
  include:
    - python: 2.7

install:
  - pip install jupyter pelican markdown


script:
  - git config --global user.email "TravisBot@nomail"
  - git config --global user.name "TravisBot"
  - git config --global push.default simple
  - git clone --recursive https://github.com/flothesof/PelicanBlog
  - make publish

