name: pelican_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter 
  - pelican 
  - markdown 
  - beautifulsoup4 
  - nbconvert 
  - ipython 
  - pip:
    - pelican-jupyter