name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env create --file environment.yml
    - name: Print current directory data
      run: |
        ls
    - name: Activate environment
      run: |
        conda activate pelican_env
    - name: Generate HTML content
      run: |
        make publish    
    - name: Clone existing blog source
      run: |
        mkdir _build && cd _build && git clone https://github.com/flothesof/flothesof.github.io.git
    - name: Print current directory data
      run: |
        ls

