name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter pelican markdown beautifulsoup4 nbconvert ipython pelican-jupyter
    - name: Print current directory data
      run: |
        ls
    - name: Generate HTML content
      run: |
        make publish    
    - name: Clone existing blog source
      run: |
        mkdir _build && cd _build && git clone https://github.com/flothesof/flothesof.github.io.git
    - name: Print current directory data
      run: |
        ls

